### ISSUE TITLE
Missing Code of Conduct

### ISSUE THREAD

**Issue by SATVIKSH** [BhavyanshJain/CPP-Problem-Solutions#12]
Hey, according to Hacktoberfest Guidlines while  participating in Hacktoberfest it is recommended to include a Code of Conduct file with your repository. I can update your repository with Code of Conduct md file if you assign me the task.

**Comment by BhavyanshJain** [comment]
Yeah! Thats a great idea. Go Ahead!

**Comment by BhavyanshJain** [comment]
Thank you for your contribution.
@SATVIKSH
